package calc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-11-04T15:47:59.669+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "Add", 
                  wsdlLocation = "http://grid.lzu.edu.cn:6060/WSMath/services/Add?wsdl",
                  targetNamespace = "http://add.fub.csw.de") 
public class Add_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://add.fub.csw.de", "Add");
    public final static QName AddHttpEndpoint = new QName("http://add.fub.csw.de", "AddHttpEndpoint");
    public final static QName AddHttpSoap11Endpoint = new QName("http://add.fub.csw.de", "AddHttpSoap11Endpoint");
    public final static QName AddHttpSoap12Endpoint = new QName("http://add.fub.csw.de", "AddHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://grid.lzu.edu.cn:6060/WSMath/services/Add?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Add_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://grid.lzu.edu.cn:6060/WSMath/services/Add?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Add_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Add_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Add_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AddPortType
     */
    @WebEndpoint(name = "AddHttpEndpoint")
    public AddPortType getAddHttpEndpoint() {
        return super.getPort(AddHttpEndpoint, AddPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddPortType
     */
    @WebEndpoint(name = "AddHttpEndpoint")
    public AddPortType getAddHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(AddHttpEndpoint, AddPortType.class, features);
    }
    /**
     *
     * @return
     *     returns AddPortType
     */
    @WebEndpoint(name = "AddHttpSoap11Endpoint")
    public AddPortType getAddHttpSoap11Endpoint() {
        return super.getPort(AddHttpSoap11Endpoint, AddPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddPortType
     */
    @WebEndpoint(name = "AddHttpSoap11Endpoint")
    public AddPortType getAddHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(AddHttpSoap11Endpoint, AddPortType.class, features);
    }
    /**
     *
     * @return
     *     returns AddPortType
     */
    @WebEndpoint(name = "AddHttpSoap12Endpoint")
    public AddPortType getAddHttpSoap12Endpoint() {
        return super.getPort(AddHttpSoap12Endpoint, AddPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddPortType
     */
    @WebEndpoint(name = "AddHttpSoap12Endpoint")
    public AddPortType getAddHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(AddHttpSoap12Endpoint, AddPortType.class, features);
    }

}
