package calc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-11-04T15:47:59.667+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://add.fub.csw.de", name = "AddPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface AddPortType {

    @WebResult(name = "return", targetNamespace = "http://add.fub.csw.de")
    @Action(input = "urn:add", output = "urn:addResponse")
    @RequestWrapper(localName = "add", targetNamespace = "http://add.fub.csw.de", className = "calc.Add")
    @WebMethod(action = "urn:add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://add.fub.csw.de", className = "calc.AddResponse")
    public java.lang.Double add(
        @WebParam(name = "d1", targetNamespace = "http://add.fub.csw.de")
        java.lang.Double d1,
        @WebParam(name = "d2", targetNamespace = "http://add.fub.csw.de")
        java.lang.Double d2
    );
}
